let
    Source = Excel.Workbook(File.Contents("C:\ImportFile.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet),
    #"Filtered Columns" = Table.SelectColumns(#"Promoted Headers",
        {"Master Account ID", "Master Account Name", "Account#", 
        "Acct Name", "Investable Cash", "Cash %", "Equity %", "Fixed Income %"}),
    #"Removed Duplicates" = Table.Distinct(#"Filtered Columns", {"Account#"})
in
    #"Removed Duplicates"
